// Code generated by "stringer -type=HttpErrorCode -linecomment"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HTTP_OK-200]
	_ = x[HTTP_NOT_FOUNT-404]
	_ = x[HTTP_SERVICE_UNAVAILABLE-503]
}

const (
	_HttpErrorCode_name_0 = "访问成功"
	_HttpErrorCode_name_1 = "404 不存在"
	_HttpErrorCode_name_2 = "503 服务端错误"
)

func (i HttpErrorCode) String() string {
	switch {
	case i == 200:
		return _HttpErrorCode_name_0
	case i == 404:
		return _HttpErrorCode_name_1
	case i == 503:
		return _HttpErrorCode_name_2
	default:
		return "HttpErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
