// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OtherClient is the client API for Other service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OtherClient interface {
	// Sends a greeting
	SayOther(ctx context.Context, in *OtherRequest, opts ...grpc.CallOption) (*OtherReply, error)
}

type otherClient struct {
	cc grpc.ClientConnInterface
}

func NewOtherClient(cc grpc.ClientConnInterface) OtherClient {
	return &otherClient{cc}
}

func (c *otherClient) SayOther(ctx context.Context, in *OtherRequest, opts ...grpc.CallOption) (*OtherReply, error) {
	out := new(OtherReply)
	err := c.cc.Invoke(ctx, "/pb.Other/SayOther", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OtherServer is the server API for Other service.
// All implementations must embed UnimplementedOtherServer
// for forward compatibility
type OtherServer interface {
	// Sends a greeting
	SayOther(context.Context, *OtherRequest) (*OtherReply, error)
	mustEmbedUnimplementedOtherServer()
}

// UnimplementedOtherServer must be embedded to have forward compatible implementations.
type UnimplementedOtherServer struct {
}

func (UnimplementedOtherServer) SayOther(context.Context, *OtherRequest) (*OtherReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayOther not implemented")
}
func (UnimplementedOtherServer) mustEmbedUnimplementedOtherServer() {}

// UnsafeOtherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OtherServer will
// result in compilation errors.
type UnsafeOtherServer interface {
	mustEmbedUnimplementedOtherServer()
}

func RegisterOtherServer(s grpc.ServiceRegistrar, srv OtherServer) {
	s.RegisterService(&Other_ServiceDesc, srv)
}

func _Other_SayOther_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OtherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OtherServer).SayOther(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Other/SayOther",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OtherServer).SayOther(ctx, req.(*OtherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Other_ServiceDesc is the grpc.ServiceDesc for Other service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Other_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Other",
	HandlerType: (*OtherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayOther",
			Handler:    _Other_SayOther_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/test.proto",
}
